# mkdocs 配置文件
# mkdocs serve  # 本地预览
# mkdocs build  # 编译
# mkdocs gh-deploy  # 自动上传至 gh-pages 分支

site_name: tkintertools # 站点名称
site_url: https://Xiaokang2022.github.io/tkintertools/ # 站点链接
site_author: Xiaokang2022 # 站点作者
site_description: tkintertools is an auxiliary development module of tkinter # 站点描述
repo_name: Xiaokang2022/tkintertools # 仓库名称
repo_url: https://github.com/Xiaokang2022/tkintertools # 仓库源地址
edit_url: https://github.com/Xiaokang2022/tkintertools # 编辑和查看文档的地址
copyright: Copyright &copy; 2022 - 2023 Xiaokang2022 # 版权信息
remote_branch: gh-pages # GitHub Pages 分支名称（此处为默认值）

markdown_extensions: # Python Markdown 官方扩展
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

theme: # 主题设置
  name: material # 第三方主题名称
  language: zh # material 语言
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - navigation.expand
    - navigation.footer
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)" # 默认主题
      primary: teal # 默认标题栏颜色
      accent: orange # 默认链接高亮颜色
      toggle:
        icon: material/brightness-auto
        name: 切换至暗色主题
    - media: "(prefers-color-scheme: light)" # 亮色主题
      scheme: default
      primary: light blue # 明亮标题栏颜色
      accent: pink # 明亮链接高亮颜色
      toggle:
        icon: material/brightness-7
        name: 切换至系统主题
    - media: "(prefers-color-scheme: dark)" # 暗色主题
      scheme: slate
      primary: black # 黑暗标题栏颜色
      accent: yellow # 黑暗链接高亮颜色
      toggle:
        icon: material/brightness-4
        name: 切换至亮色主题
  font: # 字体
    text: Microsoft YaHei # 文本
    code: consolas # 代码
  logo: "logo.png" # 徽标（要加上引号）
  favicon: "logo.png" # 网站图标
  icon:
    repo: fontawesome/brands/github
    # admonition:  # 特殊注释
    #   note: octicons/tag-16  # 笔记
    #   abstract: octicons/checklist-16
    #   info: octicons/info-16  # 说明
    #   tip: octicons/squirrel-16  # 提示
    #   success: octicons/check-16  # 成功
    #   question: octicons/question-16  # 提问
    #   warning: octicons/alert-16  # 警告
    #   failure: octicons/x-circle-16  # 失败
    #   danger: octicons/zap-16  # 危险
    #   bug: octicons/bug-16  # BUG
    #   example: octicons/beaker-16  # 举例
    #   quote: octicons/quote-16  # 引用

extra: # 额外设定
  social: # 社交联系方式（页面右下角内容）
    - icon: fontawesome/brands/github # GitHub 仓库链接
      link: https://github.com/Xiaokang2022/tkintertools/
    - icon: fontawesome/brands/python # PyPI 页面链接
      link: https://pypi.org/project/tkintertools/
  homepage: . # 徽标链接的地址（此处为根目录，即主页）

plugins: # 插件
  - search: # 唯一官方附带插件
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

nav: # 导航栏
  - Home / 主页:
      - Profile - 简介: index.md
      - Site Navigation - 站点导航: navigation.md

  - Tutorials / 教程:
      - 前言: tutorials/0-1.md
      - 第一章：安装与初识:
          - 安装 tkintertools: tutorials/1-1.md
          - 认识 tkintertools: tutorials/1-2.md
          - tkintertools 初体验: tutorials/1-3.md
      - 第二章：容器控件: tutorials/2-1.md
        # - Tk
        # - Toplevel
        # - Canvas
      - 第三章：功能控件: tutorials/3-1.md
        # - Label
        # - Button
        # - CheckButton
        # - Entry
        # - Text
        # - ProgressBar
        # - Switch
        # - ToolTip
      - 第四章：界面布局: tutorials/4-1.md
        # - Place
        # - Slide
      - 第五章：图片: tutorials/5-1.md
        # - Icon
        # - PhotoImage
      - 第六章：动画以及颜色效果: tutorials/6-1.md
        # - Animation
        # - color
      - 第七章：3D 子模块:
          - 3D 对象: tutorials/7-1.md
          - 3D 文本: tutorials/7-2.md
          - 3D 动画: tutorials/7-3.md
          - 3D 进阶: tutorials/7-4.md
      - 第八章：杂项: tutorials/8-1.md
        # - 学会一些实用的小技巧
        # - 混合使用 tkinter
      - 第九章：实战: tutorials/9-1.md
        # - 手把手实战教学
        # - 引导式实战教学
        # - 实战项目推荐

  - Documents / 文档: documents/index.md

  - News / 新闻:
      - Series 2 - 系列 2:
          - 2.6.18: news/2.6.18/News.md
          - 2.6.17: news/2.6.17/News.md
          - 2.6.16: news/2.6.16/News.md
          - 2.6.15: news/2.6.15/News.md
          - 2.6.14: news/2.6.14/News.md
          - 2.6.13: news/2.6.13/News.md
          - 2.6.12: news/2.6.12/News.md
          - 2.6.11: news/2.6.11/News.md
          - 2.6.10: news/2.6.10/News.md
          - 2.6.9: news/2.6.9/News.md
          - 2.6.8: news/2.6.8/News.md
          - 2.6.7: news/2.6.7/News.md
          - 2.6.6: news/2.6.6/News.md
      - Series 3 - 系列 3:
          - 3.0.0(pre): news/3.0.0/News.md

  - More / 更多:
      - Contribution Guide - 贡献指南: more/CONTRIBUTING.md
      - Change Log - 更新日志: more/CHANGELOG.md
      - License - 项目证书: more/LICENSE.md
